namespace YokIstatistikWeb.Models
{
    public class SehirVeriViewModel
    {
        public string Sehir { get; set; }
        public int Toplam { get; set; }

        public string ISOCode => Sehir.ToUpper() switch
        {
            "ADANA" => "TR-01",
            "ADIYAMAN" => "TR-02",
            "AFYONKARAHİSAR" => "TR-03",
            "AĞRI" => "TR-04",
            "AMASYA" => "TR-05",
            "ANKARA" => "TR-06",
            "ANTALYA" => "TR-07",
            "ARTVİN" => "TR-08",
            "AYDIN" => "TR-09",
            "BALIKESİR" => "TR-10",
            "BİLECİK" => "TR-11",
            "BİNGÖL" => "TR-12",
            "BİTLİS" => "TR-13",
            "BOLU" => "TR-14",
            "BURDUR" => "TR-15",
            "BURSA" => "TR-16",
            "ÇANAKKALE" => "TR-17",
            "ÇANKIRI" => "TR-18",
            "ÇORUM" => "TR-19",
            "DENİZLİ" => "TR-20",
            "DİYARBAKIR" => "TR-21",
            "EDİRNE" => "TR-22",
            "ELAZIĞ" => "TR-23",
            "ERZİNCAN" => "TR-24",
            "ERZURUM" => "TR-25",
            "ESKİŞEHİR" => "TR-26",
            "GAZİANTEP" => "TR-27",
            "GİRESUN" => "TR-28",
            "GÜMÜŞHANE" => "TR-29",
            "HAKKARİ" => "TR-30",
            "HATAY" => "TR-31",
            "ISPARTA" => "TR-32",
            "MERSİN" => "TR-33",
            "İSTANBUL" => "TR-34",
            "İZMİR" => "TR-35",
            "KARS" => "TR-36",
            "KASTAMONU" => "TR-37",
            "KAYSERİ" => "TR-38",
            "KIRKLARELİ" => "TR-39",
            "KIRŞEHİR" => "TR-40",
            "KOCAELİ" => "TR-41",
            "KONYA" => "TR-42",
            "KÜTAHYA" => "TR-43",
            "MALATYA" => "TR-44",
            "MANİSA" => "TR-45",
            "KAHRAMANMARAŞ" => "TR-46",
            "MARDİN" => "TR-47",
            "MUĞLA" => "TR-48",
            "MUŞ" => "TR-49",
            "NEVŞEHİR" => "TR-50",
            "NİĞDE" => "TR-51",
            "ORDU" => "TR-52",
            "RİZE" => "TR-53",
            "SAKARYA" => "TR-54",
            "SAMSUN" => "TR-55",
            "SİİRT" => "TR-56",
            "SİNOP" => "TR-57",
            "SİVAS" => "TR-58",
            "TEKİRDAĞ" => "TR-59",
            "TOKAT" => "TR-60",
            "TRABZON" => "TR-61",
            "TUNCELİ" => "TR-62",
            "ŞANLIURFA" => "TR-63",
            "UŞAK" => "TR-64",
            "VAN" => "TR-65",
            "YOZGAT" => "TR-66",
            "ZONGULDAK" => "TR-67",
            "AKSARAY" => "TR-68",
            "BAYBURT" => "TR-69",
            "KARAMAN" => "TR-70",
            "KIRIKKALE" => "TR-71",
            "BATMAN" => "TR-72",
            "ŞIRNAK" => "TR-73",
            "BARTIN" => "TR-74",
            "ARDAHAN" => "TR-75",
            "IĞDIR" => "TR-76",
            "YALOVA" => "TR-77",
            "KARABÜK" => "TR-78",
            "KİLİS" => "TR-79",
            "OSMANİYE" => "TR-80",
            "DÜZCE" => "TR-81",
            _ => null
        };
    }
}
